### PR TITLE
Facelift

### PR DESCRIPTION
**Pull request by mnoble**
Hey guys,

I did some work updating the UI a bit. I figured it'd be cool to have a similar but independent look than Rubygems.org. Most of it is really just the homepage and small bits of the other pages. I converted the styles to SASS. I moved a few things around, like the Search; I figured that'd be useful to have on any page. I also nixed the giant green/red mesh background for pass and fails, they were sorta overwhelming in my opinion.

It's just one commit and it's pretty big. Sorry about that; atomic commits were sorta hard since the UI stuff is usually pretty tightly coupled with things.

You can pull in my branch and check it out if you want. Thanks.

### CODE REVIEW

**Comment by erikh** [comment]
Pardon the expletives, but this is fucking amazing! I can't wait to integrate this.

One thing I found: the autocomplete in the search does not work. If you can fix/style this appropriately and add those commits, that'd be great.... but this is a shoe in for a design replacement.

Great work!!!

**Comment by erikh** [comment]
Also, you should credit yourself somewhere for the design.

**Comment by capoferro** [comment]
I'm a big fan of the redesign, well done. :D

The home page is particularly awesome. In general, I imagine there are a few small things to tweak, but due to the amount of work you did, that's to be expected.

Excellent work. It really gives the site the polish it needs to be a first class tool. Thank you so much for taking this initiative.

Also, I agree that you should add a link or some how take credit for your work. It's well deserved.

**Comment by mnoble** [comment]
Fixed the gem search; it was a dumb comma missing as you can see from above.

I'll wait on the credit stuff for now; I'd like to get more involved with the project in general so it'll just be a team effort ;)

**Pull request merged**
